= Ungdomsklubb-Server 
Dokumentasjon av ungdomsklubbserver

== Server informasjon 

==== Nettverk informasjon
===== Static Server IPv4

`10.0.0.1`

===== Subnet mask 

`255.0.0.0`

===== Default gateway

`10.0.0.1`

===== Virtual Switch 

Switch name: `Domain Ungdomsklubb Network Switch`

Connection type: `Internal network`

==== Servernavn 

`UngdomsklubbServer`

==== Processors 

`Intel Core i7-4800MQ CPU @ 2.70GHz`

==== Installed memory (RAM)

`2048 MB Dynamic`

==== Nr of allocated CPU cores 

`4`

==== Operating system version

`Microsoft Windows Server 2019 Standard Evaluation`

==== Hardware information 

`Microsoft Corporation Virtual Machine`

==== Server Roles installed

* `Active Directory Domain Services` +
* `DNS Server` +
* `File and Storage Services -> File and iSCSI Services -> File Server` +
* `File and Storage Services -> Storage Services` +
* `Web Server (IIS)`

==== Active Directory Configurations

===== Root domain name

`fyllingsdalenungdomsklubb.no`

===== Forest functional level

`Windows Server 2016`

===== NetBIOS domain name

`FYLLINGSDALENUN`

===== Paths

====== Database folder

`C:\Windows\NTDS`

====== Log files folder

`C:\Windows\NTDS`

====== SYSVOL folder +
`C:\Windows\SYSVOL`

== Klient PC informasjon (Den virtuelle testmaskinen)

=== Statisk IP

`10.0.0.2`

== Brukere

Brukernavn: `Administrator`

Passord: `Kake1234`

Tilganger: `root` 

== Grupper

Administrator

Bruker



== Delte mapper

=== Userfolders

Share name: `Userfolders`

Remote path to share: `\\UngdomsklubbSer\Userfolders`

Access-based enumeration: `Enabled`

Permission entries: +
Everyone: `Deny` + 
Acccess: `Full Control`

Users: `Allow` +
Access: `Change`

Quota: `1GB Limit`

=== WebServer

Navn på Mappe: `WebServer`

Permissions entries::
Administrators Allow `FULL ACCESS` +

Users Deny `FULL ACCESS`

Network location share: `\\UngdomsklubbServer.fyllingsdalenungdomsklubb.no\\WebServer`

Local location: `C:\Shares\WebServer`

== Type deling

== GPO (Group Policy)

User restrictions::
En GPO innenfor OU fyllingsdalenungdomsklubb.no, med følgende konfigurasjoner

* User configuration > Policies > Administrative Templates > Desktop > Desktop > Disable all items +

** State: `Enabled`

* User configuration > Policies > Administrative Templates > Desktop > Hide and disable all items on the desktop +

** State: `Enabled`

* User configuration > Policies > Administrative Templates > System > Prevent access to the command prompt +

** State: `Enabled`

Misc::
En GPO innenfor OU fyllingsdalenungdomsklubb.no, med følgende konfigurasjoner

* User configuration > Policies > Administrative Templates > Windows Components > Internet Explorer > Disable changing home page settings +

** State: `Enabled` +

** Home page set to: `fyllingsdalenungdomsklubb.no`



