= Logg / Tidslinje
Hva som er gjort på Ungdomsklubb Server

Her finner du en systematisk oversikt over hva som er gjort på Ungdomsklubb Servere'n, med dato nedover. 
Relevant informasjon, som kan være nyttig for andre å se. For å løse uventede problemer raskere og mer effektivt. 

'''

=== Opprettelse av Windows Server 2019 (HYPER-V)
`10.02.2019`

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+
Alle funksjoner hittil fungerer som det skal.

** [*] *Har du testet at alt virker - og hvordan testet du?*
+
Testing er gjennomført, serveren starter opp som normalt. 

* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Skiftelse av IPv4 adresse
`11.02.2019`

Adressen ble skiftet til `10.0.0.1` og Subnet mask: `255.0.0.0` 

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+
Alle funksjoner hittil fungerer som det skal.

** [*] *Har du testet at alt virker - og hvordan testet du?*
+
Testing er gjennomført, serveren starter opp som normalt. 

* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Skiftelse av Server navn / PC navn
`12.02.2019`

Navn ble skiftet til `UngdomsklubbServer`

Beskrivelse ble skiftet til `A server for Ungdomskluben in Fyllingsdalen`

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+
Serveren måtte ha restart for at navnet skulle tre inn. 

** [*] *Har du testet at alt virker - og hvordan testet du?*
+
Server navnet vises i Server Manager.

* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Installasjon av Server Roller
`12.02.2019`

`Active Directory Domain Services` +
`DNS Server` +
`File and Storage Services -> File and iSCSI Services -> File Server` +
`File and Storage Services -> Storage Services` +
`Web Server (IIS)` +

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+
Serveren måtte ha restart for at det skulle tre inn

** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Konfigurasjon av Active Directory Domain Services
`12.02.2019`

Root domain name `fyllingsdalenungdomsklubb.no`

Forest functional level `Windows Server 2016`

NetBIOS domain name `FYLLINGSDALENUN`


* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+
Serveren måtte ha restart for at det skulle tre inn

** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Oprettelse av første nye bruker i AD
`12.02.2019`

Firstname: `Isak` +
Last name: `Myhrvold` +
Initials: `Mr` +
Full name: `Isak Mr. Myhrvold` +
User logon name: `isamyh@fyllingsdalenungdomsklubb.no` +
User logon name (pre- Windows 2000): `FYLLINGSDALENUN\isamyh` +

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+


** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''
=== Opprettelse av Windows 10 DEV environment (HYPER-V)
`12.02.2019`

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+


** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Opprettelse av virtuell switch (HYPER-V)
`14.02.2019`

Switch name: `Domain Ungdomsklubb Network Switch`

Connection type: `Internal network`

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+


** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Melde inn Windows 10 Dev i domene
`14.02.2019`

Klient fikk statisk ip: `10.0.0.2`

Klient default gateway ble satt til: `10.0.0.1`

Server default gateway satt til `10.0.0.1`

Klient subnet mask satt til: `255.255.255.0`

Server subnet mask satt til: `255.255.255.0`

* [ ] *Ble planen fulgt?*

** [*] Om du ikke fulgte planen? 

*** [*] Hvorfor ikke? 
Fikk ett problem når jeg skulle melde inn klienten i domene. Den ville ikke kontakte serveren gjennom det interne nettverkskortet.

*** [*] Hva forandret du på? 
Løsningen var å gi klienten en statisk IPv4 adresse, og standard gateway til serverens statiske ip. 

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+


** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Opprettelse av test bruker
`15.02.2019`

Firstname: `Bjørnstjerne` +
Last name: `Bjørnson` +
Full name: `Bjørnstjerne Bjørnson` +
User logon name: `bjøbjø@fyllingsdalenungdomsklubb.no` +
User logon name (pre- Windows 2000): `FYLLINGSDALENUN\bjøbjø` +

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+


** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Opprettelse av GPO User restrictions
`20.02.2019`

Navn på GPO: `User restrictions`
Konfigurasjoner

* User configuration > Policies > Administrative Templates > Desktop > Desktop > Disable all items `ENABLED`

* User configuration > Policies > Administrative Templates > Desktop > Hide and disable all items on the desktop `ENABLED`

* User configuration > Policies > Administrative Templates > System > Prevent access to the command prompt `ENABLED`

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+


** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

=== Opprettelse av GPO Misc
`20.02.2019`

Navn på GPO: `Misc`

Konfigurasjoner

* User configuration > Policies > Administrative Templates > Windows Components > Internet Explorer > Disable changing home page settings `ENABLED`

** Home page set to: `localhost`

* [*] *Ble planen fulgt?*

* [*] *Kontrollmetoder samt funksjonsprøving, eventuelt feilretting*
+


** [*] *Har du testet at alt virker - og hvordan testet du?*
+


* [*] *Gjennomførte HMS - tiltak underveis*
+
Husket å drikke vann, samhandlet med medelever. 

'''

== Mal
Dato

* [*] Ble planen fulgt? 

** [ ] Om du ikke fulgte planen? 

*** [ ] Hvorfor ikke? 

*** [ ] Hva forandret du på? 

* [*] Kontrollmetoder samt funksjonsprøving, eventuelt feilretting

** [*] Har du testet at alt virker - og hvordan testet du?

** [ ] Om ikke noe virket

*** [ ] Hva var feilen?

*** [ ] Hvor fant du løsningen?

* [*] Gjennomførte HMS - tiltak underveis

** [*] Bevegelse avveksling i arbeidsoppgaver, samarbeid med andre. Husk å drikke


